import React from "react";
import Head from "next/head";

const Heading = () => {
  return (
    <Head>
      <title>FUDO</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/Logo.png" />
    </Head>
  );
};

export default Heading;
