import Menu from "../components/Menu/Menu";
import Head from "next/head";
import Hero from "../components/Hero/Hero";
import Layout from "../components/Layout";
import Services from "../components/Services/Services";
import { client } from "../lib/client";

export default function Home({ pizzas }) {
  return (
    <Layout>
      <div>
        <Head>
          <title>FUDO</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Logo.png" />
        </Head>
        {/* body */}
        <main>
          <Hero />
          <Services />
          <Menu data={pizzas} />
        </main>
      </div>
    </Layout>
  );
}

export const getServerSideProps = async () => {
  const query = '*[_type=="pizza"]';
  const pizzas = await client.fetch(query);
  return {
    props: { pizzas },
  };
};
